#!/bin/sh

# Convert a text file to an mp3 using tts

INPUT_TXT=$1
OUTPUT_WAV=${INPUT_TXT/txt/wav}
OUTPUT_MP3=${INPUT_TXT/txt/mp3}
OUTPUT_WAV_FAST=${INPUT_TXT/.txt/_fast.wav}
OUTPUT_MP3_FAST=${INPUT_TXT/.txt/_fast.mp3}
flite -f "${INPUT_TXT}" -o "$OUTPUT_WAV"    2>&1 > /dev/null

# Speed up the audio
sox "${OUTPUT_WAV}" "${OUTPUT_WAV_FAST}" tempo 1.5

rm "$OUTPUT_WAV"

echo "OUTPUT: $OUTPUT_MP3_FAST"
# Convert wav to mp3
ffmpeg -nostdin -loglevel  quiet -i "$OUTPUT_WAV_FAST"  -acodec libmp3lame -ar 44100 -ab 64000 -y "$OUTPUT_MP3_FAST"

rm "$OUTPUT_WAV_FAST"


echo DONE!


