#!/usr/bin/env bash

# audio device support on mac os isn't available with flite so to read
# stdin we need to output to wav and open it to get somewhat expected
# behavior

# USAGE: echo "read this aloud" | flite-wrapper

TEMP_OUT_WAV=$(mktemp /tmp/flite.XXXXXXXXXX).wav
TEMP_OUT_WAV_READ=${TEMP_OUT_WAV}.read.wav

while read -r text; do
    flite -t "$text" -o ${TEMP_OUT_WAV} && \
        sox ${TEMP_OUT_WAV} ${TEMP_OUT_WAV_READ} tempo 1.5 && \
        mpv --no-video --no-audio-display ${TEMP_OUT_WAV_READ} && \
        rm ${TEMP_OUT_WAV//.wav/}*
done
